#
# MAINTAINER        Michael Joe <michael_joe@126.com>
# DOCKER-VERSION    1.0.0
#
# Dockerizing Ubuntu 14.01: Dockerfile for building nginx
#
FROM	joedockerhub/ubuntu
MAINTAINER	Michael Joe  <michael_joe@126.com>
ENV	TZ "Asia/Shanghai"
WORKDIR	/root/

RUN apt-get -y install nginx
RUN mkdir /var/www/html -p











ENTRYPOINT []
